name: Pull Request

on:
  pull_request:

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install packages
        run: npm ci

      - name: Check lint
        run: npm run lint

      - name: Check format
        run: npm run format:check

      - name: Run tests
        run: npm run test
